name: CI
on: [push]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --frozen-lockfile --prefer-offline && yarn global add @lhci/cli@latest
        
      - name: Build project
        run: yarn run build
        
      - name: Run lighthouse
        run: lhci autorun --config=.github/workflows/assertions.json --upload.target=temporary-public-storage
