name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install project dependencies
        run: yarn --prefer-offline && yarn global add @lhci/cli
        
      - name: Build project
        run: yarn run build
        
      - name: Run lighthouse
        run: lhci autorun --config=.github/workflows/assertions.json --upload.target=temporary-public-storage
